#!/usr/bin/env sh
#
# A rofi powered menu to execute power related action.
# Uses: amixer mpc poweroff reboot rofi rofi-prompt

power_off=''
reboot=''
lock=''
suspend='鈴'
log_out=''

prompt='/home/mike/.config/rofi/scripts/rofi-prompt'

chosen=$(printf '%s;%s;%s;%s;%s\n' "$power_off" "$reboot" "$lock" \
"$suspend" "$log_out" \
    | rofi -theme-str '@import "power.rasi"' \
           -dmenu \
           -sep ';' \
           -selected-row 2)

case "$chosen" in
    "$power_off") poweroff;;
    "$reboot")    reboot;;
    "$lock")      /home/mike/scripts/lock.sh;;
	"$suspend")
        # Pause music and mute volume before suspending.
        mpc --quiet pause
        amixer set Master mute
		systemctl suspend
    ;;

    "$log_out")  i3-msg exit;;
    *) exit 1 ;;
esac
