#!/usr/bin/env sh
#
# Rofi powered menu to take a screenshot of the whole screen, a selected area or
# the active window. The image is then saved and copied to the clipboard.
# Uses: date maim notify-send rofi xclip xdotool

save_location="$HOME/Pictures/screenshots"
screenshot_path="$save_location/$(date +'%Y-%m-%d-%H%M%S').png"

screen=''
area=''
window=''

chosen=$(printf '%s;%s;%s\n' "$screen" "$area" "$window" \
    | rofi -theme-str '@import "screenshot.rasi"' \
           -dmenu \
           -sep ';' \
           -selected-row 1)

case "$chosen" in
    "$screen") scrot $screenshot_path;;
    "$area")   flameshot gui -p $screenshot_path ;;
    "$window") scrot -s $screenshot_path ;;
    *)         exit 1 ;;
esac

# The variable is used as a command's options, so it shouldn't be quoted.
# shellcheck disable=2086
maim --hidecursor --quiet --quality=3 --format='png' $extra_args "$screenshot_path" && {
    notify-send "Screenshot saved as <i>$screenshot_path</i>"

    xclip -selection clipboard -target 'image/png' -in "$screenshot_path"
}
